// Android widget hosts refuse to honor android:updatePeriodMillis below
// ~30 minutes (Android enforces this floor), so getting the flashcard to
// rotate every ~5 minutes needs a real alarm outside that mechanism. This
// plugin adds:
//
//   1. A small Kotlin BroadcastReceiver (WidgetAutoRefreshReceiver) that,
//      each time it fires, sends an explicit APPWIDGET_UPDATE broadcast to
//      both flashcard widget providers (which is what react-native-android-
//      widget listens for to re-run the JS task handler), then reschedules
//      itself ~5 minutes out.
//   2. A manifest entry for that receiver, plus BOOT_COMPLETED so the chain
//      resumes after a device restart.
//   3. One line in MainApplication.onCreate to kick off the first alarm as
//      soon as the app is opened, so the user doesn't have to reboot their
//      phone to see it start working.
//
// Requires react-native-android-widget's own plugin to run first (it
// creates the ".widget.<Name>" provider classes this receiver targets).

const {
  withAndroidManifest,
  withMainApplication,
  withDangerousMod,
  AndroidConfig,
} = require("@expo/config-plugins");
const fs = require("fs");
const path = require("path");

const REFRESH_INTERVAL_MS = 5 * 60 * 1000; // ~5 minutes
const RECEIVER_CLASS = "WidgetAutoRefreshReceiver";
const WIDGET_NAMES = ["IELTSFlashcard", "GlossarFlashcard"];

function receiverKotlinSource(packageName) {
  const widgetClassNames = WIDGET_NAMES.map((n) => `"${packageName}.widget.${n}"`).join(", ");

  return `package ${packageName}

import android.appwidget.AppWidgetManager
import android.app.AlarmManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.ComponentName
import android.content.Context
import android.content.Intent

// Auto-generated by withWidgetAutoRefresh — do not hand-edit; re-run
// \`npx expo prebuild\` to regenerate after changing the plugin.
class ${RECEIVER_CLASS} : BroadcastReceiver() {

  companion object {
    const val ACTION_REFRESH = "${packageName}.WIDGET_AUTO_REFRESH"
    const val REFRESH_INTERVAL_MS = ${REFRESH_INTERVAL_MS}L
    val WIDGET_PROVIDER_CLASSES = listOf(${widgetClassNames})

    fun scheduleNext(context: Context) {
      val alarmManager = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
      val intent = Intent(context, ${RECEIVER_CLASS}::class.java).apply { action = ACTION_REFRESH }
      val pendingIntent = PendingIntent.getBroadcast(
        context,
        0,
        intent,
        PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
      )
      val triggerAt = System.currentTimeMillis() + REFRESH_INTERVAL_MS
      try {
        alarmManager.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, triggerAt, pendingIntent)
      } catch (e: SecurityException) {
        // Missing SCHEDULE_EXACT_ALARM on some OEMs/OS versions — fall back
        // to an inexact alarm rather than crash; still refreshes, just not
        // on the dot.
        alarmManager.set(AlarmManager.RTC_WAKEUP, triggerAt, pendingIntent)
      }
    }
  }

  override fun onReceive(context: Context, intent: Intent) {
    val appWidgetManager = AppWidgetManager.getInstance(context)

    for (className in WIDGET_PROVIDER_CLASSES) {
      val component = ComponentName(context.packageName, className)
      val ids = appWidgetManager.getAppWidgetIds(component)
      if (ids.isNotEmpty()) {
        val updateIntent = Intent(AppWidgetManager.ACTION_APPWIDGET_UPDATE).apply {
          component = ComponentName(context.packageName, className)
          putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS, ids)
        }
        context.sendBroadcast(updateIntent)
      }
    }

    // Chain the next alarm — also covers the BOOT_COMPLETED case, since that
    // intent lands here too and this schedules the recurring cycle.
    scheduleNext(context)
  }
}
`;
}

function withWidgetAutoRefreshSource(config) {
  return withDangerousMod(config, [
    "android",
    async (config) => {
      const packageName = config.android?.package;
      if (!packageName) {
        return config;
      }
      const packagePath = packageName.replace(/\./g, "/");
      const dir = path.join(
        config.modRequest.platformProjectRoot,
        "app/src/main/java",
        packagePath
      );
      fs.mkdirSync(dir, { recursive: true });
      fs.writeFileSync(
        path.join(dir, `${RECEIVER_CLASS}.kt`),
        receiverKotlinSource(packageName)
      );
      return config;
    },
  ]);
}

function withWidgetAutoRefreshManifest(config) {
  return withAndroidManifest(config, (config) => {
    const app = config.modResults.manifest.application?.[0];
    if (!app) return config;

    if (!Array.isArray(app.receiver)) app.receiver = [];

    const alreadyPresent = app.receiver.some(
      (r) => r.$?.["android:name"] === `.${RECEIVER_CLASS}`
    );
    if (!alreadyPresent) {
      app.receiver.push({
        $: {
          "android:name": `.${RECEIVER_CLASS}`,
          "android:exported": "false",
        },
        "intent-filter": [
          {
            action: [{ $: { "android:name": "android.intent.action.BOOT_COMPLETED" } }],
          },
        ],
      });
    }

    config.modResults = AndroidConfig.Permissions.ensurePermissions(config.modResults, [
      "android.permission.RECEIVE_BOOT_COMPLETED",
      "android.permission.SCHEDULE_EXACT_ALARM",
    ]);

    return config;
  });
}

function withWidgetAutoRefreshKickoff(config) {
  return withMainApplication(config, (config) => {
    const packageName = config.android?.package;
    if (!packageName) return config;

    const importLine = `import ${packageName}.${RECEIVER_CLASS}`;
    const kickoffLine = `    ${RECEIVER_CLASS}.scheduleNext(this)`;

    let contents = config.modResults.contents;

    if (!contents.includes(importLine)) {
      contents = contents.replace(
        /(package [^\n]+\n)/,
        `$1\n${importLine}\n`
      );
    }

    if (!contents.includes(`${RECEIVER_CLASS}.scheduleNext`)) {
      // Drop the kickoff at the end of onCreate(), right after super.onCreate(),
      // which every Expo-generated MainApplication.kt contains verbatim.
      contents = contents.replace(
        /(override fun onCreate\(\)\s*\{\s*\n\s*super\.onCreate\(\)\n)/,
        `$1${kickoffLine}\n`
      );
    }

    config.modResults.contents = contents;
    return config;
  });
}

module.exports = function withWidgetAutoRefresh(config) {
  config = withWidgetAutoRefreshSource(config);
  config = withWidgetAutoRefreshManifest(config);
  config = withWidgetAutoRefreshKickoff(config);
  return config;
};
