package com.sunless_7.cardsssss

import android.appwidget.AppWidgetManager
import android.app.AlarmManager
import android.app.PendingIntent
import android.content.BroadcastReceiver
import android.content.ComponentName
import android.content.Context
import android.content.Intent

// Auto-generated by withWidgetAutoRefresh — do not hand-edit; re-run
// `npx expo prebuild` to regenerate after changing the plugin.
class WidgetAutoRefreshReceiver : BroadcastReceiver() {

  companion object {
    const val ACTION_REFRESH = "com.sunless_7.cardsssss.WIDGET_AUTO_REFRESH"
    const val REFRESH_INTERVAL_MS = 300000L
    val WIDGET_PROVIDER_CLASSES = listOf("com.sunless_7.cardsssss.widget.IELTSFlashcard", "com.sunless_7.cardsssss.widget.GlossarFlashcard")

    fun scheduleNext(context: Context) {
      val alarmManager = context.getSystemService(Context.ALARM_SERVICE) as AlarmManager
      val intent = Intent(context, WidgetAutoRefreshReceiver::class.java).apply { action = ACTION_REFRESH }
      val pendingIntent = PendingIntent.getBroadcast(
        context,
        0,
        intent,
        PendingIntent.FLAG_UPDATE_CURRENT or PendingIntent.FLAG_IMMUTABLE
      )
      val triggerAt = System.currentTimeMillis() + REFRESH_INTERVAL_MS
      try {
        alarmManager.setExactAndAllowWhileIdle(AlarmManager.RTC_WAKEUP, triggerAt, pendingIntent)
      } catch (e: SecurityException) {
        // Missing SCHEDULE_EXACT_ALARM on some OEMs/OS versions — fall back
        // to an inexact alarm rather than crash; still refreshes, just not
        // on the dot.
        alarmManager.set(AlarmManager.RTC_WAKEUP, triggerAt, pendingIntent)
      }
    }
  }

  override fun onReceive(context: Context, intent: Intent) {
    val appWidgetManager = AppWidgetManager.getInstance(context)

    for (className in WIDGET_PROVIDER_CLASSES) {
      val component = ComponentName(context.packageName, className)
      val ids = appWidgetManager.getAppWidgetIds(component)
      if (ids.isNotEmpty()) {
        val updateIntent = Intent(AppWidgetManager.ACTION_APPWIDGET_UPDATE).apply {
          component = ComponentName(context.packageName, className)
          putExtra(AppWidgetManager.EXTRA_APPWIDGET_IDS, ids)
        }
        context.sendBroadcast(updateIntent)
      }
    }

    // Chain the next alarm — also covers the BOOT_COMPLETED case, since that
    // intent lands here too and this schedules the recurring cycle.
    scheduleNext(context)
  }
}
